services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: recorderApi_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recorder
      MYSQL_USER: Admin
      MYSQL_PASSWORD: password

      restart: always

volumes:
  mysql-data-volume:
